[package]
name = "aoc21"
version = "0.1.0"
edition = "2021"
authors = ["assert0 <assert0@githumb.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.1"
regex = "1.5.4"
lazy_static = "1.4.0"
vec-tree = "0.1.2"